showmanager/urls.py
from django.conf.urls import *
from django.views.generic import ListView
from . import views

urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/$', views.show_detail.as_view(), name='DetailView'),
    #url(r'^(?P<id>\d+)/$', views.show_detail),
    url(r'^$', views.index.as_view(), name='index'),
]
"""
urlpatterns = patterns('',
    #(r'^performers/(?P<id>\d+)/$', 'luke.showmanager.views.performer_detail'),
    #(r'^performers/$', 'luke.showmanager.views.performer_list'),
    (r'^(?P<id>\d+)/$', 'showmanager.views.show_detail'),
    (r'^$', ListView.as_view(model=show,)),
        url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
)
"""

studio/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve

admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
]

urlpatterns += i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),  # NOQA
url(r'^classes-and-workshops/', include('coursemanager.urls', namespace='courses')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns

showmanager/models.py
from django.db import models
from django.conf import settings
import recurrence.fields

class show(models.Model):
    show_name       = models.CharField(max_length=120)
    show_date       = models.DateField()
    show_end_date   = models.DateField(null=True)
    venue_id        = models.ForeignKey('location.Location', null=True)
    show_start      = models.TimeField()
    show_end_time   = models.TimeField()
    show_doors      = models.TimeField(null=True)
    show_recurring  = recurrence.fields.RecurrenceField(null=True)
    show_image = models.ImageField(upload_to='show_images')
    show_notes           = models.TextField(db_column='Notes', blank=True)
    show_ticket_link = models.CharField(blank=True, null=True, max_length=250)
    show_host   = models.ForeignKey('auth.User')

    def __str__(self):
        return self.show_name
    class Meta:
        db_table = 'sm_show'
        ordering    = ['show_date']

class act(models.Model):
    performer       = models.ForeignKey('auth.User')
    show_name       = models.ForeignKey('show')
    song            = models.CharField(max_length=255, blank=False, default="undecided")
    introducer      = models.ForeignKey('auth.User', related_name="introducer", blank=True,  null=True)
    kitten_id       = models.ForeignKey('auth.User', related_name="kitten_id", blank=True, null=True)
    order           = models.IntegerField(blank=False, default="100")
    act_intro       = models.TextField(blank=True)
    stage_prep      = models.TextField(blank=True)
    music_sent      = models.BooleanField(default=False)
    act_notes       = models.TextField(blank=True)
    lighting_notes  = models.TextField(blank=True)
    start_onstage    = models.BooleanField(default=False)
    is_featured     = models.BooleanField(default=False)

    #def __unicode__(self):
    #    return u'%s %s %s %s %s' % (self.song, self.user, self.introducer, self.kitten_id, self.show_name)

    class Meta:
        db_table     = 'sm_act'
        ordering    = ['show_name', 'order']

showmanager/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.views import generic
from .models import show, act
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.template import RequestContext

#def index(request):

    #shows_list = show.objects.all().order_by('-date')
    #return render_to_response('shows/shows_list.html', {'shows_list': shows_list})
    #return render_to_response('base.html', context_instance = RequestContext(request))

class index(generic.ListView):
    template_name = 'showmanager/index.html'
    context_object_name = 'show_list'

    def get_queryset(self):
        return show.objects.order_by('show_date')[:25]



#@login_required
#def performer_detail(request, id):
#    return list_detail.object_detail(
#        request,
#        queryset = performer.objects.all(),
#    )
#    performer_detail.__doc__ = list_detail.object_detail.__doc__

#@login_required
#def performer_list(request):
#    return list_detail.object_list(
#        request,
#        queryset = performer.objects.all(),
#    )
#    performer_list.__doc__ = list_detail.object_list.__doc__

#def show_detail(request, id):
#    return list_detail.object_detail(
#        request,
#        queryset = show.objects.all(),
#        object_id = id,
#    )
#    show_detail.__doc__ = list_detail.object_detail.__doc__
class show_detail(generic.DetailView):
#    pass
    model = show
    template_name = 'showmanager/show_detail.html'



def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/musiclib')

showmanager/templates/showmanager/acts_in_show.html
{% extends "base.html" %}

{% block content %}
<ul>
{% for show_act in object_list %}
    <li>{{show_act.name}}</li>
{% endfor %}
</ul>
{% endblock %}

showmanager/templates/showmanager/performer_list_page.html
{% extends "base.html" %}

{% block content %}
<ul>
{% for performer in object_list %}
    <li>{{performer.fname}} {{performer.lname}}</li>
{% endfor %}
</ul>
{% endblock %}

showmanager/templates/showmanager/show_detail.html
{% extends "base.html" %}

{% block title %} {{ object.show_name }} - Van Ella Productions {% endblock %}

{% block content %}

<h2> {{ object.show_name }} {{ object.show_date }}</h2>
<img src="/media/{{ object.show_image }}" class="courseheader"><br />
<h3>{{ object.venue_id }},  {{ object.venue_id.location_address }}</h3>
Doors: {{ object.show_doors }}<br />
Show: {{ object.show_start }}
<p />
<!--
<h3>Featuring:</h3>


{% for act in object.act_set.all %}
    {{ act.performer.first_name}} {{ act.performer.last_name }}<br />
{% endfor %}
will be needed later for full show manager implementation
-->

<br /><br />
{{ object.show_notes | safe }}

<p />
Tickets available at <a href="{{ object.show_ticket_link }}">Eventbrite</a> 


 {% endblock content %}

showmanager/templates/showmanager/show_list.html
{% extends "base.html" %}

{% block title %}Upcoming Shows - Van Ella Productions {% endblock %}

{% block content %}

<h2>Upcoming Shows </h2>
<ul>
{% for object in object_list %}
    <li><a href="{{ object.id }}">{{ object.show_name }}</a> - {{ object.show_date }}</li>

{% endfor %}


{% endblock %}

showmanager/templates/showmanager/shows_list.html
{% extends "base.html" %}

{% block title %} Show List {% endblock %}

{% block content %}

<ul>
{% for object in object_list %}
    <li>{{ object.show_name}}</li>
{% endfor %}


{% endblock %}