coursemanager/urls.py
from django.conf.urls import url

from . import views
app_name = 'coursemanager'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]

studio/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve

admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
]

urlpatterns += i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),  # NOQA
url(r'^classes-and-workshops/', include('coursemanager.urls', namespace='courses')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns

coursemanager/models.py
from django.db import models
import datetime
import recurrence.fields

DOW = (('1', 'Sunday'),
      ('2', 'Monday'),
      ('3', 'Tuesday'),
      ('4', 'Wednesday'),
      ('5', 'Thursday'),
      ('6', 'Friday'),
      ('7', 'Saturday'))

class Course(models.Model):
    course_name = models.CharField(blank=False, null=False, max_length=250)
    course_slug = models.SlugField(unique=True)
    course_description = models.TextField(blank=False, null=False)
    course_start_time = models.TimeField(blank=False, null=False)
    course_end_time = models.TimeField(blank=False, null=False)
    course_days_of_week = models.CharField(max_length=1, choices=DOW, blank=True)
    course_all_day = models.BooleanField(default=False)
    custom_start_date = models.DateField(blank=True, null=True)
    custom_end_date = models.DateField(blank=True, null=True)
    session_id = models.ForeignKey('Session')
    course_private = models.BooleanField(default=False)
    course_spaces = models.IntegerField(default=15)
    course_date_created = models.DateTimeField(blank=True, null=False, auto_now=True)
    course_date_modified = models.DateTimeField(blank=True, null=False, auto_now=True)
    course_instructor = models.ForeignKey('auth.User')
    course_image = models.ImageField(upload_to='course_images')
    course_price = models.IntegerField(blank=True, null=True, default=160)
    location        = models.ForeignKey('location.Location', null=True)
    category_id = models.ForeignKey('Category')
    course_recurring  = recurrence.fields.RecurrenceField(null=True)
    is_workshop = models.BooleanField(default=False)
    dropins = models.BooleanField(default=True)
    dropin_price = models.IntegerField(default=20)
    course_ticket_link = models.CharField(blank=True, max_length=250)
    publish_date = models.DateField(blank=False, default=datetime.datetime.now)
    isActive = models.BooleanField(default=True)
    
    def __str__(self):
        return self.course_name

class CourseImage(models.Model):
    course_image = models.ImageField()
    
    def _str__(self):
        return self.courseimage_id

class Session(models.Model):
    session_name = models.CharField(blank=False, null=False, max_length=250)
    session_start_date = models.DateField(blank=False, null=False)
    session_end_date = models.DateField(blank=False, null=False)
    session_notes = models.TextField(blank=True)

    def __str__(self):
        return self.session_name

class Category(models.Model):
    category_name = models.CharField(blank=False, null=False, max_length=250)
    category_slug = models.CharField(max_length=100, blank=False, null=False)

    def __str__(self):
        return self.category_name
        

coursemanager/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
#from django.conf.urls import reverse
from django.views import generic
from .models import Course, Session


class IndexView(generic.ListView):
    template_name = 'coursemanager/index.html'
    context_object_name = 'latest_courses_list'

    def get_queryset(self):
        """Return the last five published courses."""
        return Course.objects.filter(isActive=True).order_by('category_id','course_name')[:30]


    
class DetailView(generic.DetailView):
    model = Course
    #courserecur = Course.objects.get(pk=1)
    #text_rules_inclusion = []

    #for rule in courserecur.course_recurring.rrules:
     #   text_rules_inclusion.append(rule.to_text())
    
    template_name = 'coursemanager/detail.html'

coursemanager/templates/coursemanager/base.html
{% extends 'base.html' %}

{% block content %}
    {% block coursemanager_content %}
    {% endblock %}
{% endblock %}

coursemanager/templates/coursemanager/detail.html
{% extends "base.html" %}

 {% block content %}
<h1>{{ course.course_name }}</h1>with {{ course.course_instructor }}<p />
<img src="/media/{{ course.course_image }}" class="courseheader"><br />

{{ course.course_description | safe }}<p />
<p/>
Held at: {{ course.location.location_name }} {{ course.location.location_address }}<br>
Time:  {{ course.course_start_time }} to {{ course.course_end_time }}<br>
Price: $ {{ course.course_price }}<br>
Dropins Allowed: {{ course.dropins }}, ${{ course.dropin_price }}<br />
<!-- need recurrence rules here
course.course_recurrence.rrules -->
<!-- turn on once switched to eventbrite
<hr>
Once you have determined what courses you wish to take, you can sign up on 

<a href="{{ course.course_ticket_link }}">to pay online</a> and add the classes you want or register <a href="/offline-registration">here</a> to pay offline.
<p />
-->
 {% endblock content %}

coursemanager/templates/coursemanager/index.html
{% extends "base.html" %}

 {% block content %}


<!-- new version -->
{% if latest_courses_list %}
<h1>Winter 2018</h1>
<!-- <h2>Feb 5-Mar 31</h2> -->
{% regroup latest_courses_list by category_id  as courses_by_category %}

{% for c in courses_by_category %}
  <h2>{{c.grouper}}</h2>
  <ul>
    {% for course in c.list %}
     
      <li> <a href="/classes-and-workshops/{{ course.id }}/">{{ course.course_name }}</a> with {{ course.course_instructor }},
          
          {% if course.custom_start_date %} {{ course.custom_start_date }} {% else %}
          {{ course.get_course_days_of_week_display }}s  {% endif %} at {{ course.course_start_time }}<p /></li>
    {% endfor %}
  </ul>
{% endfor %}
{% else %}
    <p>No courses are available.</p>
{% endif %}

 {% endblock content %}